### ISSUE TITLE
Question 8-byte alignment PTX code

### ISSUE THREAD

**Issue by SimeonEhrig** [hfinkel/llvm-project-cxxjit#13]
Hi,

I adapt your fatbinary code generation for the CUDA extension of the [Cling](https://github.com/root-project/cling/pull/284). Thereby I found the following code:

https://github.com/hfinkel/llvm-project-cxxjit/blob/87bbc36c9d8b532137b7091f709d05116d16ca08/clang/lib/CodeGen/JIT.cpp#L1407-L1412

If I understand it correctly, the size of `DevAsm` should be a multiple of 8 and the last 8-byte block should end with `'\0'`.

Your implementation generates code with the size n*7+1+1.

I developed the following solution:
```c++
DevCD->DevAsm += std::string(7 - (DevCD->DevAsm.size() % 8), ' ') + '\0';
```
Did I find a bug or do I have a wrong idea?

**Comment by lxwithgod** [comment]
are you ok on cuda?
I can never succeed cuda jit，if __global__ function is template ,the caller of this kernel is clangjit template,I use nvprof ,I can't see this kernel,but cudaLuanch,cudaSetupArgument.
I use cuda10.0/cuda9.2,gcc/g++ 7/8,clangjit-9.0 ,please tell me  how you success .

**Comment by SimeonEhrig** [comment]
@lxwithgod 
I'm not sure what do you mean with templated global functions, because the issue is about how to align PTX Code.

**Comment by hfinkel** [comment]
Thanks, @SimeonEhrig, I'll look at this soon.

**Comment by hfinkel** [comment]
> Did I find a bug or do I have a wrong idea?

Yes, that logic seems incorrect. I've updated it just to use null padding (after always adding at least one null) and CUDA seems happy with that.
