### ISSUE TITLE
Can this be done with Specialization Constant

### ISSUE THREAD

**Issue by uyongw** [hfinkel/llvm-project-cxxjit#15]
Is  this related to the [SPIR-V Specialization Constant](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpSpecConstant) feature? 

There is a [SYCL proposal](https://github.com/codeplaysoftware/standards-proposals/blob/master/spec-constant/index.md) that comes with the following 2 user APIs that can do the similar trick: `::spec_constant` to declare a specialization constant variable and the value is determined (or changed) in runtime by `::set_spec_constant`.

**Comment by hfinkel** [comment]
> Is this related to the SPIR-V Specialization Constant feature?

It's not. There is a subset of this which can be done with specialization constants. However, those, in terms of the syntax of the language, are not constants, and can't affect the types being used (i.e., can't make an array in a structure whose number of elements depends on the specialization constant value), and can't change the underlying data types (e.g., float vs. double vs. MyNumber<5, 6, float>).

**Comment by uyongw** [comment]
@hfinkel Thanks for the clarification. Agree with you on type specialization. 

One more question, if we have this nice feature in C++, can we compile the source with compiler A and run that code with a runtime JITter from compiler B? Or do we have to define a standard IR (SPIR-V for example) as interfaces between static compiler and runtime compiler?
