### ISSUE TITLE
Build Fail when NVPTX things are missing

### ISSUE THREAD

**Issue by calewis** [hfinkel/llvm-project-cxxjit#7]
I don't have any Nvidia tools installed on my machine. So get the build to work I need to comment out the following (located around JIT.cpp:905). I am not sure if I am missing a CMake argument or if the code just needs to check if NV stuff is available before calling this.  
```c++
       if (!InitializedDevTarget) {
          // LLVMInitializeNVPTXTargetInfo();
          // LLVMInitializeNVPTXTarget();
          // LLVMInitializeNVPTXTargetMC();
          // LLVMInitializeNVPTXAsmPrinter();

          InitializedDevTarget = true;
        }
```

**Comment by hfinkel** [comment]
So, you don't need to have any NV tools in order to build the NVPTX target support, but nevertheless, it is certainly possible to build LLVM without it. I'll try to devise a workaround...

**Comment by calewis** [comment]
Ahh indeed I forgot that I had put `-DLLVM_TARGETS_TO_BUILD="X86"` in my build script oops.

**Comment by hfinkel** [comment]
Should be fixed now.
